import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/src/components/ui/HomePage";
import { Bubblegum_Sans } from "next/font/google";
import { Toaster } from "@/src/components/ui/toaster";
import { Toaster as Sonner } from "@/src/components/ui/sonner";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { TooltipProvider } from "@/src/components/ui/tooltip";
// import clsx from "clsx";
import { Providers } from "@/src/components/providers";
import Image from "next/image";
import waves from "@/public/wave.svg";
import waves2 from "@/public/wave copy.svg";
import Link from "next/link";

const bubblegum = Bubblegum_Sans({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-bubble",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const queryClient = new QueryClient();

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-zinc-50 antialiased relative overflow-x-hidden min-h-sreen`}
			>
				{/* <Providers> */}
				<header
					className={`sticky top-0 bg-primary flex font-bubble text-accent mx-12 rounded-b-2xl py-2 px-8 z-20 justify-between
				${bubblegum.className}
			`}
				>
					<div>
						<Link href={"/"} className="hover:opacity-80">
							<h1 className="text-2xl md:text-6xl">WestAfriDeal</h1>
						</Link>
					</div>
					<NavBar />
				</header>
				{children}

				{/* </Providers> */}
				<Image
					src={waves}
					alt="marketplace"
					width={1920}
					height={1080}
					className="lg:hidden block bottom-0 sticky"
				/>{" "}
				<Image
					src={waves2}
					alt="marketplace"
					width={1920}
					height={1080}
					className="hidden lg:block bottom-0 sticky"
				/>
			</body>
		</html>
	);
}
